### PR TITLE
v2.2.0 - new major version for mempool-js

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
### v2.2.0 - new major version of the mempool-js

- Change package.json.
- Reorganize README.md.
- Default export for CommonJS and ES6 Modules.
- Change default variable to mempoolJS.
- Organize the API and WS providers.
- Split websocket connection types: client and server.
- Refactor folder structure.
- Add apiEndpoint and websocketEndpoint to Mempool initial config.
- Add brownserify feature to support standalone JS applications.
- Add MIT LICENSE

### CODE REVIEW

**Review by jaonoctus — APPROVED** [review]
Great approach, by using composables functions.

Nice work man!

**Comment by MiguelMedeiros** [comment]
> Great approach, by using composables functions.
> 
> Nice work man!

Big thanks to you, @jaonoctus !
Thanks for the PR approval! :heart:

**Comment by wiz** [comment]
Maybe we should make the version number of mempool-js match the version of mempool, so how about v2.2 ?

**Comment by MiguelMedeiros** [comment]
> Maybe we should make the version number of mempool-js match the version of mempool, so how about v2.2 ?

I've read this doc about semantic versioning packages:
https://docs.npmjs.com/about-semantic-versioning

image

Imagine a situation that a minor release occur on the mempool main project and there is no change on any endpoint of the API. There is no need to make a new patch here, right?

Maybe this will cause some unnecessary versioning patching.

**Comment by jaonoctus** [comment]
> Imagine a situation that a minor release occur on the mempool main project and there is no change on any endpoint of the API. There is no need to make a new patch here, right?

Agree. The [mempool-js](https://github.com/mempool/mempool-js) is related to the [mempool-backend](https://github.com/mempool/mempool/tree/master/backend) but it is just a standalone package. It should have its own versioning

> I've read this doc about semantic versioning packages:
> https://docs.npmjs.com/about-semantic-versioning

 https://semver.org

**Comment by wiz** [comment]
Yes, that's why I suggested v2.2 instead of v2.2.0 - we can agree to increment the minor version for API changes so you don't have to care if we increment the patch version 😉

**Comment by MiguelMedeiros** [comment]
> Yes, that's why I suggested v2.2 instead of v2.2.0 - we can agree to increment the minor version for API changes so you don't have to care if we increment the patch version 😉

Ok! I'll change the package.json version to 2.2.0!

**Review by softsimon — APPROVED** [review]

**Comment by softsimon** [comment]
utACK

**Review by wiz — APPROVED** [review]
ACK
:rocket:

**Pull request merged**
